language: cpp
compiler:
  - gcc
  - clang
git:
  submodules: false
cache: apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq scons libglew-dev libsdl2-dev libsdl2-image-dev
  - sudo apt-get install -qq libbullet-dev libvorbis-dev libcurl4-gnutls-dev
script:
  - scons
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - core13@gmx.net
    on_success: change
    on_failure: always